name: MLflow Workflow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/rahmatreyhan05/telco-customer-churn-mlflow.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      # =========================
      # CHECKOUT
      # =========================

      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # SETUP PYTHON
      # =========================

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      # =========================
      # CHECK ENVIRONMENT
      # =========================

      - name: Check environment
        run: |
          python --version
          pip --version

      # =========================
      # INSTALL DEPENDENCIES
      # =========================

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # =========================
      # RUN MLFLOW PROJECT
      # =========================

      - name: Run MLflow Project
        run: |
          mlflow run . --env-manager=local

      # =========================
      # SAVE MLFLOW RUN ID
      # =========================

      - name: Save MLflow Run ID
        run: |
          echo "MLflow Run ID:"
          cat mlflow_run_id.txt

      # =========================
      # UPLOAD ARTIFACT
      # =========================

      - name: Upload MLflow Run ID
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-id
          path: mlflow_run_id.txt

      - name: Show MLflow Model URI
        run: |
          echo "MLflow Model URI:"
          cat mlflow_model_uri.txt

      # =========================
      # BUILD DOCKER IMAGE
      # =========================

      - name: Build Docker image from MLflow model
        run: |
          MODEL_URI=$(cat mlflow_model_uri.txt)

          echo "Using MLflow Model URI: $MODEL_URI"

           mlflow models build-docker \
              --model-uri "$MODEL_URI" \
              --name "telco-customer-churn"

      # =========================
      # LOGIN DOCKER HUB
      # =========================

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # =========================
      # TAG DOCKER IMAGE
      # =========================

      - name: Tag Docker image
        run: |
          docker tag telco-customer-churn:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/telco-customer-churn:latest

      # =========================
      # PUSH DOCKER IMAGE
      # =========================

      - name: Push Docker image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/telco-customer-churn:latest
